import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { afterEach, describe, expect, it } from "vitest";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const scriptsRoot = path.join(projectRoot, "scripts");
const temporaryRoots: string[] = [];
const versionUpdateTimeout = 30_000;

function commandExists(command: string): boolean {
  const result = spawnSync(command, ["--version"], {
    encoding: "utf8",
    windowsHide: true,
  });

  return result.status === 0;
}

const hasReleaseToolchain = commandExists("pwsh") && commandExists("cargo");
const describeReleaseTooling = hasReleaseToolchain ? describe : describe.skip;

type FixtureOptions = {
  cargoLockIncludesArcheion?: boolean;
  changelogIncludesRelease?: boolean;
};

function createFixture({
  cargoLockIncludesArcheion = true,
  changelogIncludesRelease = true,
}: FixtureOptions = {}): string {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "archeion-release-tooling-"));
  temporaryRoots.push(root);

  fs.mkdirSync(path.join(root, "src-tauri", "src"), { recursive: true });

  fs.writeFileSync(
    path.join(root, "package.json"),
    `${JSON.stringify(
      {
        name: "archeion",
        private: true,
        version: "0.3.0",
      },
      null,
      2,
    )}\n`,
  );
  fs.writeFileSync(
    path.join(root, "package-lock.json"),
    `${JSON.stringify(
      {
        name: "archeion",
        version: "0.3.0",
        lockfileVersion: 3,
        requires: true,
        packages: {
          "": {
            name: "archeion",
            version: "0.3.0",
          },
        },
      },
      null,
      2,
    )}\n`,
  );
  fs.writeFileSync(
    path.join(root, "src-tauri", "Cargo.toml"),
    `[package]\nname = "archeion"\nversion = "0.3.0"\nedition = "2021"\n\n[[bin]]\nname = "archeion"\npath = "src/main.rs"\n`,
  );
  fs.writeFileSync(
    path.join(root, "src-tauri", "Cargo.lock"),
    cargoLockIncludesArcheion
      ? `# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = "archeion"\nversion = "0.3.0"\n`
      : `# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n`,
  );
  fs.writeFileSync(path.join(root, "src-tauri", "src", "main.rs"), "fn main() {}\n");
  fs.writeFileSync(
    path.join(root, "src-tauri", "tauri.conf.json"),
    `${JSON.stringify({ productName: "Archeion", version: "0.3.0" }, null, 2)}\n`,
  );
  fs.writeFileSync(
    path.join(root, "CHANGELOG.md"),
    changelogIncludesRelease
      ? `# Changelog\n\n## [Unreleased]\n\n## [0.3.0] - 2026-07-12\n\n- Fixture release.\n\n[Unreleased]: https://github.com/TommyMoonn/archeion/compare/v0.3.0...HEAD\n[0.3.0]: https://github.com/TommyMoonn/archeion/compare/v0.2.0...v0.3.0\n`
      : `# Changelog\n\n## [Unreleased]\n`,
  );

  return root;
}

function runPowerShell(scriptName: string, args: string[]) {
  return spawnSync(
    "pwsh",
    [
      "-NoProfile",
      "-ExecutionPolicy",
      "Bypass",
      "-File",
      path.join(scriptsRoot, scriptName),
      ...args,
    ],
    {
      cwd: projectRoot,
      encoding: "utf8",
      windowsHide: true,
    },
  );
}

function combinedOutput(result: ReturnType<typeof runPowerShell>): string {
  return `${result.stdout ?? ""}\n${result.stderr ?? ""}`;
}

function readVersions(root: string) {
  const packageJson = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8")) as {
    version: string;
  };
  const packageLock = JSON.parse(fs.readFileSync(path.join(root, "package-lock.json"), "utf8")) as {
    packages: Record<string, { version: string }>;
  };
  const cargoToml = fs.readFileSync(path.join(root, "src-tauri", "Cargo.toml"), "utf8");
  const cargoLock = fs.readFileSync(path.join(root, "src-tauri", "Cargo.lock"), "utf8");
  const tauriConfig = JSON.parse(
    fs.readFileSync(path.join(root, "src-tauri", "tauri.conf.json"), "utf8"),
  ) as { version: string };

  return {
    packageJson: packageJson.version,
    packageLock: packageLock.packages[""].version,
    cargoToml: cargoToml.match(/^version\s*=\s*"([^"]+)"/m)?.[1],
    cargoLock: cargoLock.match(
      /^\[\[package\]\]\s*\r?\nname\s*=\s*"archeion"\s*\r?\nversion\s*=\s*"([^"]+)"/m,
    )?.[1],
    tauriConfig: tauriConfig.version,
  };
}

afterEach(() => {
  for (const root of temporaryRoots.splice(0)) {
    fs.rmSync(root, { force: true, recursive: true });
  }
});

describeReleaseTooling("release tooling", () => {
  it("validates package-lock files with the empty root package key", () => {
    const root = createFixture();
    const result = runPowerShell("check-release.ps1", [
      "-ProjectRoot",
      root,
      "-Tag",
      "v0.3.0",
      "-RequireChangelogEntry",
    ]);

    expect(combinedOutput(result)).toContain("Release configuration is valid.");
    expect(combinedOutput(result)).toContain("Tag:     v0.3.0");
    expect(result.status).toBe(0);
  });

  it("rejects a release tag that does not match the application version", () => {
    const root = createFixture();
    const result = runPowerShell("check-release.ps1", ["-ProjectRoot", root, "-Tag", "v0.4.0"]);

    expect(result.status).not.toBe(0);
    expect(combinedOutput(result)).toContain("Expected 'v0.3.0'");
  });

  it("rejects release validation when the changelog entry is missing", () => {
    const root = createFixture({ changelogIncludesRelease: false });
    const result = runPowerShell("check-release.ps1", [
      "-ProjectRoot",
      root,
      "-RequireChangelogEntry",
    ]);

    expect(result.status).not.toBe(0);
    expect(combinedOutput(result)).toContain(
      "CHANGELOG.md does not contain a dated [0.3.0] release section.",
    );
  });

  it(
    "updates all application version sources as one transaction",
    () => {
      const root = createFixture();
      const result = runPowerShell("set-version.ps1", ["0.4.0-beta.1", "-ProjectRoot", root]);

      expect(combinedOutput(result)).toContain("Updated Archeion to version 0.4.0-beta.1.");
      expect(result.status).toBe(0);
      expect(readVersions(root)).toEqual({
        packageJson: "0.4.0-beta.1",
        packageLock: "0.4.0-beta.1",
        cargoToml: "0.4.0-beta.1",
        cargoLock: "0.4.0-beta.1",
        tauriConfig: "0.4.0-beta.1",
      });
    },
    versionUpdateTimeout,
  );

  it(
    "restores every version file when an update step fails",
    () => {
      const root = createFixture({ cargoLockIncludesArcheion: false });
      const versionPaths = [
        "package.json",
        "package-lock.json",
        "src-tauri/Cargo.toml",
        "src-tauri/Cargo.lock",
        "src-tauri/tauri.conf.json",
      ];
      const before = new Map(
        versionPaths.map((relativePath) => [
          relativePath,
          fs.readFileSync(path.join(root, relativePath), "utf8"),
        ]),
      );

      const result = runPowerShell("set-version.ps1", ["0.4.0", "-ProjectRoot", root]);

      expect(result.status).not.toBe(0);
      expect(combinedOutput(result)).toContain(
        "Unable to locate src-tauri/Cargo.lock Archeion package.version.",
      );
      for (const relativePath of versionPaths) {
        expect(fs.readFileSync(path.join(root, relativePath), "utf8")).toBe(
          before.get(relativePath),
        );
      }
    },
    versionUpdateTimeout,
  );
});
