import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { afterEach, describe, expect, it } from "vitest";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const scriptsRoot = path.join(projectRoot, "scripts");
const temporaryRoots: string[] = [];
const releaseProcessTimeout = 30_000;

function commandExists(command: string): boolean {
  const result = spawnSync(command, ["--version"], {
    encoding: "utf8",
    windowsHide: true,
  });

  return result.status === 0;
}

const hasReleaseToolchain = commandExists("pwsh") && commandExists("cargo");
const describeReleaseTooling = hasReleaseToolchain ? describe : describe.skip;

type FixtureOptions = {
  version?: string;
  changelogIncludesRelease?: boolean;
  invalidCargoMetadata?: boolean;
  releaseNote?: string | null;
};

function createFixture({
  version = "0.3.0",
  changelogIncludesRelease = true,
  invalidCargoMetadata = false,
  releaseNote = `<!-- release-note: v${version}; date: 2026-07-12 -->\n\n## Changes\n\n- Fixture release.\n`,
}: FixtureOptions = {}): string {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "archeion-release-tooling-"));
  temporaryRoots.push(root);

  fs.mkdirSync(path.join(root, "src-tauri", "src"), { recursive: true });

  fs.writeFileSync(
    path.join(root, "package.json"),
    `${JSON.stringify(
      {
        name: "archeion",
        private: true,
        version,
      },
      null,
      2,
    )}\n`,
  );
  fs.writeFileSync(
    path.join(root, "package-lock.json"),
    `${JSON.stringify(
      {
        name: "archeion",
        version,
        lockfileVersion: 3,
        requires: true,
        packages: {
          "": {
            name: "archeion",
            version,
          },
        },
      },
      null,
      2,
    )}\n`,
  );
  fs.writeFileSync(
    path.join(root, "src-tauri", "Cargo.toml"),
    invalidCargoMetadata
      ? `[package]\nname = "archeion"\nversion = "${version}"\nedition = "2021"\n\n[dependencies\n`
      : `[package]\nname = "archeion"\nversion = "${version}"\nedition = "2021"\n\n[[bin]]\nname = "archeion"\npath = "src/main.rs"\n`,
  );
  fs.writeFileSync(
    path.join(root, "src-tauri", "Cargo.lock"),
    `# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = "archeion"\nversion = "${version}"\n`,
  );
  fs.writeFileSync(path.join(root, "src-tauri", "src", "main.rs"), "fn main() {}\n");
  fs.writeFileSync(
    path.join(root, "src-tauri", "tauri.conf.json"),
    `${JSON.stringify({ productName: "Archeion", version }, null, 2)}\n`,
  );
  fs.writeFileSync(
    path.join(root, "CHANGELOG.md"),
    changelogIncludesRelease
      ? `# Changelog\n\n## [Unreleased]\n\n## [${version}] - 2026-07-12\n\n- Fixture release.\n\n[Unreleased]: https://github.com/TommyMoonn/archeion/compare/v${version}...HEAD\n[${version}]: https://github.com/TommyMoonn/archeion/compare/v0.2.0...v${version}\n`
      : `# Changelog\n\n## [Unreleased]\n`,
  );

  if (releaseNote !== null) {
    fs.mkdirSync(path.join(root, "release-notes"));
    fs.writeFileSync(path.join(root, "release-notes", `v${version}.md`), releaseNote);
  }

  return root;
}

function createBundleFixture(options: FixtureOptions = {}) {
  const version = options.version ?? "0.3.0";
  const root = createFixture(options);
  const bundleRoot = path.join(root, "bundle");
  const outputDirectory = path.join(root, "artifacts", "windows");
  fs.mkdirSync(path.join(bundleRoot, "nsis"), { recursive: true });
  fs.mkdirSync(path.join(bundleRoot, "msi"), { recursive: true });
  fs.writeFileSync(
    path.join(bundleRoot, "nsis", `Archeion_${version}_x64-setup.exe`),
    "fixture NSIS installer",
  );
  fs.writeFileSync(
    path.join(bundleRoot, "msi", `Archeion_${version}_x64_en-US.msi`),
    "fixture MSI installer",
  );
  addSignatureFixtures(bundleRoot, version);

  return { root, bundleRoot, outputDirectory };
}

function stageFixture(
  { root, bundleRoot, outputDirectory }: ReturnType<typeof createBundleFixture>,
  extraArgs: string[] = [],
) {
  return runPowerShell("stage-windows-release.ps1", [
    "--project",
    root,
    "--bundle-dir",
    bundleRoot,
    "--output",
    outputDirectory,
    ...extraArgs,
  ]);
}

function createStagedInstallerFixture() {
  const fixture = createBundleFixture();
  const result = stageFixture(fixture);
  if (result.status !== 0) {
    throw new Error(`Could not stage installer fixture: ${combinedOutput(result)}`);
  }

  return fixture;
}

function addSignatureFixtures(bundleRoot: string, version = "0.3.0") {
  fs.writeFileSync(
    path.join(bundleRoot, "nsis", `Archeion_${version}_x64-setup.exe.sig`),
    "fixture NSIS signature",
  );
  fs.writeFileSync(
    path.join(bundleRoot, "msi", `Archeion_${version}_x64_en-US.msi.sig`),
    "fixture MSI signature",
  );
}

function releaseToolingEnvironment(overrides: NodeJS.ProcessEnv = {}): NodeJS.ProcessEnv {
  const environment = { ...process.env };

  delete environment.GITHUB_REF_NAME;
  delete environment.GITHUB_REF_TYPE;

  return { ...environment, ...overrides };
}

function runPowerShell(
  scriptName: string,
  args: string[],
  environmentOverrides: NodeJS.ProcessEnv = {},
) {
  return spawnSync(
    "pwsh",
    [
      "-NoProfile",
      "-ExecutionPolicy",
      "Bypass",
      "-File",
      path.join(scriptsRoot, scriptName),
      ...args,
    ],
    {
      cwd: projectRoot,
      encoding: "utf8",
      env: releaseToolingEnvironment(environmentOverrides),
      windowsHide: true,
    },
  );
}

function combinedOutput(result: ReturnType<typeof runPowerShell>): string {
  return `${result.stdout ?? ""}\n${result.stderr ?? ""}`;
}

function expectStagingOutputDirectory(output: string, outputDirectory: string) {
  const reportedDirectory = output.match(/^[ \t]+Output[ \t]+([^\r\n]+)\r?$/m)?.[1];
  if (!reportedDirectory) throw new Error("Missing staging output directory summary");

  // Windows temp paths can use an 8.3 alias while PowerShell reports the long path.
  expect(fs.realpathSync.native(reportedDirectory)).toBe(fs.realpathSync.native(outputDirectory));
}

function expectFragmentsInOrder(output: string, fragments: string[]) {
  let previousIndex = -1;
  for (const fragment of fragments) {
    const currentIndex = output.indexOf(fragment);
    expect(currentIndex, `missing output fragment: ${fragment}`).toBeGreaterThan(previousIndex);
    previousIndex = currentIndex;
  }
}

function sha256(contents: string): string {
  return createHash("sha256").update(contents).digest("hex");
}

function readVersions(root: string) {
  const packageJson = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8")) as {
    version: string;
  };
  const packageLock = JSON.parse(fs.readFileSync(path.join(root, "package-lock.json"), "utf8")) as {
    packages: Record<string, { version: string }>;
  };
  const cargoToml = fs.readFileSync(path.join(root, "src-tauri", "Cargo.toml"), "utf8");
  const cargoLock = fs.readFileSync(path.join(root, "src-tauri", "Cargo.lock"), "utf8");
  const tauriConfig = JSON.parse(
    fs.readFileSync(path.join(root, "src-tauri", "tauri.conf.json"), "utf8"),
  ) as { version: string };

  return {
    packageJson: packageJson.version,
    packageLock: packageLock.packages[""].version,
    cargoToml: cargoToml.match(/^version\s*=\s*"([^"]+)"/m)?.[1],
    cargoLock: cargoLock.match(
      /^\[\[package\]\]\s*\r?\nname\s*=\s*"archeion"\s*\r?\nversion\s*=\s*"([^"]+)"/m,
    )?.[1],
    tauriConfig: tauriConfig.version,
  };
}

afterEach(() => {
  for (const root of temporaryRoots.splice(0)) {
    fs.rmSync(root, { force: true, recursive: true });
  }
});

describeReleaseTooling("release tooling", { timeout: releaseProcessTimeout }, () => {
  it.each(["1.6.0", "1.6.1"])(
    "stages and independently verifies the bootstrap/future updater asset set for %s",
    (version) => {
      const fixture = createBundleFixture({ version });
      const result = stageFixture(fixture);
      expect(result.status, combinedOutput(result)).toBe(0);
      const manifest = JSON.parse(
        fs.readFileSync(path.join(fixture.outputDirectory, "latest.json"), "utf8"),
      );
      expect(manifest.version).toBe(version);
      expect(manifest.notes).toContain("Fixture release.");
      expect(manifest.pub_date).toBe("2026-07-12T00:00:00Z");
      expect(Object.keys(manifest.platforms).sort()).toEqual([
        "windows-x86_64-msi",
        "windows-x86_64-nsis",
      ]);
      for (const [family, asset] of [
        ["nsis", "Archeion-Setup-x64.exe"],
        ["msi", "Archeion-x64.msi"],
      ]) {
        expect(manifest.platforms[`windows-x86_64-${family}`]).toEqual({
          url: `https://github.com/TommyMoonn/archeion/releases/download/v${version}/${asset}`,
          signature: fs.readFileSync(path.join(fixture.outputDirectory, `${asset}.sig`), "utf8"),
        });
      }
      const verified = runPowerShell("verify-windows-release.ps1", [
        "--project",
        fixture.root,
        "--artifacts-dir",
        fixture.outputDirectory,
      ]);
      expect(verified.status, combinedOutput(verified)).toBe(0);
    },
  );
  it("validates package-lock files with the empty root package key", () => {
    const root = createFixture();
    const result = runPowerShell("check-release.ps1", [
      "--project",
      root,
      "--tag",
      "v0.3.0",
      "--require-changelog",
    ]);

    expect(combinedOutput(result)).toContain("Release configuration is valid");
    expect(combinedOutput(result)).toMatch(/Version\s+0\.3\.0/);
    expect(combinedOutput(result)).toMatch(/Tag\s+v0\.3\.0/);
    expect(result.status).toBe(0);
  });

  it("rejects a package-lock top-level version that differs from its root package", () => {
    const root = createFixture();
    const lockPath = path.join(root, "package-lock.json");
    const lock = JSON.parse(fs.readFileSync(lockPath, "utf8")) as { version: string };
    lock.version = "0.2.9";
    fs.writeFileSync(lockPath, `${JSON.stringify(lock, null, 2)}\n`);

    const result = runPowerShell("check-release.ps1", ["--project", root]);
    expect(result.status).not.toBe(0);
    expect(combinedOutput(result)).toContain(
      "package-lock.json top-level version does not match the root package version.",
    );
  });

  it("keeps legacy PowerShell flags compatible", () => {
    const root = createFixture();
    const result = runPowerShell("check-release.ps1", [
      "-ProjectRoot",
      root,
      "-Tag",
      "v0.3.0",
      "-RequireChangelogEntry",
    ]);

    expect(combinedOutput(result)).toContain("Release configuration is valid");
    expect(result.status).toBe(0);
  });

  it.each([
    "apply-chatgpt-zip.ps1",
    "package-changed-files.ps1",
    "restore-chatgpt-import.ps1",
    "stage-windows-bundles.ps1",
  ])("keeps the legacy %s entry point", (scriptName) => {
    const result = runPowerShell(scriptName, ["--help"]);

    expect(result.status).toBe(0);
    expect(combinedOutput(result)).toContain("Usage:");
  });

  it("validates an inherited GitHub release tag when no explicit tag is supplied", () => {
    const root = createFixture();
    const result = runPowerShell("check-release.ps1", ["--project", root], {
      GITHUB_REF_NAME: "v0.3.0",
      GITHUB_REF_TYPE: "tag",
    });

    expect(combinedOutput(result)).toContain("Release configuration is valid");
    expect(combinedOutput(result)).toMatch(/Tag\s+v0\.3\.0/);
    expect(result.status).toBe(0);
  });

  it(
    "rejects a release tag that does not match the application version",
    () => {
      const root = createFixture();
      const result = runPowerShell("check-release.ps1", ["--project", root, "--tag", "v0.4.0"]);

      expect(result.status).not.toBe(0);
      expect(combinedOutput(result)).toContain("Expected 'v0.3.0'");
    },
    releaseProcessTimeout,
  );

  it(
    "rejects release validation when the changelog entry is missing",
    () => {
      const root = createFixture({ changelogIncludesRelease: false });
      const result = runPowerShell("check-release.ps1", ["--project", root, "--require-changelog"]);

      expect(result.status).not.toBe(0);
      expect(combinedOutput(result)).toContain(
        "CHANGELOG.md does not contain a dated [0.3.0] release section.",
      );
    },
    releaseProcessTimeout,
  );

  it("requires the current version's tracked release note for release readiness", () => {
    const root = createFixture({ releaseNote: null });
    const result = runPowerShell("check-release.ps1", ["--project", root, "--require-changelog"]);

    expect(result.status).not.toBe(0);
    expect(combinedOutput(result)).toContain("v0.3.0.md: release note is missing.");
  });

  it("rejects release-note metadata that disagrees with the application version", () => {
    const root = createFixture({
      releaseNote:
        "<!-- release-note: v0.4.0; date: 2026-07-12 -->\n\n## Changes\n\n- Fixture release.\n",
    });
    const result = runPowerShell("check-release.ps1", ["--project", root, "--require-changelog"]);

    expect(result.status).not.toBe(0);
    expect(combinedOutput(result)).toContain(
      "header version v0.4.0 does not match filename v0.3.0",
    );
  });

  it(
    "stages stable public installer names and matching checksums",
    () => {
      const root = createFixture();
      const bundleRoot = path.join(root, "bundle");
      const outputDirectory = path.join(root, "artifacts", "windows");
      const nsisContents = "fixture NSIS installer";
      const msiContents = "fixture MSI installer";

      fs.mkdirSync(path.join(bundleRoot, "nsis"), { recursive: true });
      fs.mkdirSync(path.join(bundleRoot, "msi"), { recursive: true });
      fs.writeFileSync(path.join(bundleRoot, "nsis", "Archeion_0.3.0_x64-setup.exe"), nsisContents);
      fs.writeFileSync(path.join(bundleRoot, "msi", "Archeion_0.3.0_x64_en-US.msi"), msiContents);
      addSignatureFixtures(bundleRoot);

      const result = runPowerShell("stage-windows-release.ps1", [
        "--project",
        root,
        "--bundle-dir",
        bundleRoot,
        "--output",
        outputDirectory,
      ]);

      expect(result.status).toBe(0);
      const output = combinedOutput(result);
      expectFragmentsInOrder(output, [
        "[1/4] Validating release metadata",
        "[2/4] Locating Windows installers",
        "[3/4] Staging installers",
        "[4/4] Writing checksum manifest",
        "Windows release staged",
      ]);
      expect(output).toMatch(/EXE\s+Archeion-Setup-x64\.exe \(\d+ B\)/);
      expect(output).toMatch(/MSI\s+Archeion-x64\.msi \(\d+ B\)/);
      expect(output).toMatch(/Checksums\s+SHA256SUMS\.txt \(\d+ B\)/);
      expectStagingOutputDirectory(output, outputDirectory);
      expect(fs.readdirSync(outputDirectory).sort()).toEqual([
        "Archeion-Setup-x64.exe",
        "Archeion-Setup-x64.exe.sig",
        "Archeion-x64.msi",
        "Archeion-x64.msi.sig",
        "SHA256SUMS.txt",
        "latest.json",
      ]);
      expect(fs.readFileSync(path.join(outputDirectory, "Archeion-Setup-x64.exe"), "utf8")).toBe(
        nsisContents,
      );
      expect(fs.readFileSync(path.join(outputDirectory, "Archeion-x64.msi"), "utf8")).toBe(
        msiContents,
      );
      expect(
        fs.readFileSync(path.join(outputDirectory, "SHA256SUMS.txt"), "utf8").trim().split(/\r?\n/),
      ).toEqual([
        `${sha256(nsisContents)}  Archeion-Setup-x64.exe`,
        `${sha256("fixture NSIS signature")}  Archeion-Setup-x64.exe.sig`,
        `${sha256(msiContents)}  Archeion-x64.msi`,
        `${sha256("fixture MSI signature")}  Archeion-x64.msi.sig`,
        `${sha256(fs.readFileSync(path.join(outputDirectory, "latest.json"), "utf8"))}  latest.json`,
      ]);
      expect(
        JSON.parse(fs.readFileSync(path.join(outputDirectory, "latest.json"), "utf8")),
      ).toEqual({
        version: "0.3.0",
        notes: "- Fixture release.",
        pub_date: "2026-07-12T00:00:00Z",
        platforms: {
          "windows-x86_64-nsis": {
            url: "https://github.com/TommyMoonn/archeion/releases/download/v0.3.0/Archeion-Setup-x64.exe",
            signature: "fixture NSIS signature",
          },
          "windows-x86_64-msi": {
            url: "https://github.com/TommyMoonn/archeion/releases/download/v0.3.0/Archeion-x64.msi",
            signature: "fixture MSI signature",
          },
        },
      });
    },
    releaseProcessTimeout,
  );

  it.skipIf(process.platform !== "win32")(
    "matches staging output by directory identity across Windows short-path aliases",
    ({ skip }) => {
      const root = createFixture();
      const longDirectory = fs.realpathSync.native(root);
      const result = spawnSync(
        "pwsh",
        [
          "-NoProfile",
          "-Command",
          "$ErrorActionPreference = 'Stop'; (New-Object -ComObject Scripting.FileSystemObject).GetFolder($env:ARCHEION_TEST_DIRECTORY).ShortPath",
        ],
        {
          encoding: "utf8",
          env: { ...process.env, ARCHEION_TEST_DIRECTORY: longDirectory },
          windowsHide: true,
        },
      );
      expect(result.status, result.stderr).toBe(0);
      const shortDirectory = result.stdout.trim();
      if (shortDirectory === longDirectory) skip("Windows 8.3 short-path aliases are unavailable");
      expect(fs.realpathSync.native(shortDirectory)).toBe(longDirectory);

      expectStagingOutputDirectory(`  Output       ${longDirectory}\r\n`, shortDirectory);
      expectStagingOutputDirectory(`  Output       ${shortDirectory}\r\n`, longDirectory);

      const otherDirectory = path.join(root, "other");
      fs.mkdirSync(otherDirectory);
      expect(() =>
        expectStagingOutputDirectory(`  Output       ${longDirectory}\r\n`, otherDirectory),
      ).toThrow();
      expect(() => expectStagingOutputDirectory(longDirectory, longDirectory)).toThrow(
        "Missing staging output directory summary",
      );
    },
  );

  it(
    "verifies the staged installer bundle and accepts an unchanged rerun",
    () => {
      const { root, outputDirectory } = createStagedInstallerFixture();
      const before = fs
        .readdirSync(outputDirectory)
        .map((name) => [name, sha256(fs.readFileSync(path.join(outputDirectory, name), "utf8"))]);

      for (let attempt = 0; attempt < 2; attempt += 1) {
        const result = runPowerShell("verify-windows-release.ps1", [
          "--artifacts-dir",
          outputDirectory,
          "--project",
          root,
        ]);
        expect(result.status).toBe(0);
        const output = combinedOutput(result);
        expectFragmentsInOrder(output, [
          "[1/3] Checking expected asset set",
          "[2/3] Verifying asset checksums",
          "[3/3] Verifying update manifest",
          "Windows release verified",
        ]);
        expect(output).toMatch(/EXE\s+Archeion-Setup-x64\.exe \(\d+ B\)/);
        expect(output).toMatch(/MSI\s+Archeion-x64\.msi \(\d+ B\)/);
        expect(output).toMatch(/Checksums\s+SHA256SUMS\.txt \(\d+ B\)/);
      }

      const after = fs
        .readdirSync(outputDirectory)
        .map((name) => [name, sha256(fs.readFileSync(path.join(outputDirectory, name), "utf8"))]);
      expect(after).toEqual(before);
    },
    releaseProcessTimeout,
  );

  it.each([
    [
      "changed installer",
      (directory: string) =>
        fs.appendFileSync(path.join(directory, "Archeion-Setup-x64.exe"), "tampered"),
    ],
    [
      "missing installer",
      (directory: string) => fs.rmSync(path.join(directory, "Archeion-x64.msi")),
    ],
    ["missing checksum", (directory: string) => fs.rmSync(path.join(directory, "SHA256SUMS.txt"))],
    [
      "changed signature",
      (directory: string) =>
        fs.appendFileSync(path.join(directory, "Archeion-x64.msi.sig"), "tampered"),
    ],
    [
      "changed manifest",
      (directory: string) => fs.appendFileSync(path.join(directory, "latest.json"), "tampered"),
    ],
    [
      "extra asset",
      (directory: string) => fs.writeFileSync(path.join(directory, "unexpected.txt"), "extra"),
    ],
  ])(
    "rejects a %s before the candidate artifact can be accepted",
    (_case, modify) => {
      const { root, outputDirectory } = createStagedInstallerFixture();
      modify(outputDirectory);
      const result = runPowerShell("verify-windows-release.ps1", [
        "--artifacts-dir",
        outputDirectory,
        "--project",
        root,
      ]);
      expect(result.status).not.toBe(0);
    },
    releaseProcessTimeout,
  );

  it("rejects a missing MSI before staging or artifact upload", () => {
    const root = createFixture();
    const bundleRoot = path.join(root, "bundle");
    const outputDirectory = path.join(root, "artifacts", "windows");
    fs.mkdirSync(path.join(bundleRoot, "nsis"), { recursive: true });
    fs.mkdirSync(path.join(bundleRoot, "msi"), { recursive: true });
    fs.writeFileSync(
      path.join(bundleRoot, "nsis", "Archeion_0.3.0_x64-setup.exe"),
      "fixture NSIS installer",
    );

    const result = runPowerShell("stage-windows-release.ps1", [
      "--project",
      root,
      "--bundle-dir",
      bundleRoot,
      "--output",
      outputDirectory,
    ]);
    expect(result.status).not.toBe(0);
    expect(combinedOutput(result)).toContain("Expected exactly one MSI installer");
    expect(fs.existsSync(outputDirectory)).toBe(false);
  });

  it.each([
    ["missing signature", "nsis/Archeion_0.3.0_x64-setup.exe.sig", "remove"],
    ["empty signature", "msi/Archeion_0.3.0_x64_en-US.msi.sig", "empty"],
    ["wrong-version signature", "nsis/Archeion_0.3.0_x64-setup.exe.sig", "rename"],
    ["extra signature", "msi/orphan.msi.sig", "extra"],
    ["duplicate installer", "nsis/Archeion_0.3.0_x64-copy-setup.exe", "extra"],
    ["duplicate MSI installer", "msi/Archeion_0.3.0_x64_fr-FR.msi", "extra"],
    ["wrong-version installer", "nsis/Archeion_0.3.0_x64-setup.exe", "rename"],
    ["empty installer", "msi/Archeion_0.3.0_x64_en-US.msi", "empty"],
  ])(
    "rejects %s without replacing existing output",
    (_case, relativePath, mutation) => {
      const fixture = createBundleFixture();
      fs.mkdirSync(fixture.outputDirectory, { recursive: true });
      const previous = path.join(fixture.outputDirectory, "latest.json");
      fs.writeFileSync(previous, "previous output");
      const filename = path.join(fixture.bundleRoot, relativePath);
      if (mutation === "remove") fs.rmSync(filename);
      else if (mutation === "rename") fs.renameSync(filename, filename.replace("0.3.0", "10.3.0"));
      else fs.writeFileSync(filename, mutation === "empty" ? "" : "extra fixture asset");
      const result = stageFixture(fixture);
      expect(result.status, combinedOutput(result)).not.toBe(0);
      expect(fs.readdirSync(fixture.outputDirectory)).toEqual(["latest.json"]);
      expect(fs.readFileSync(previous, "utf8")).toBe("previous output");
    },
    releaseProcessTimeout,
  );

  it(
    "preserves previous output when canonical release metadata cannot generate a manifest",
    () => {
      const fixture = createBundleFixture({ releaseNote: null });
      fs.mkdirSync(fixture.outputDirectory, { recursive: true });
      fs.writeFileSync(path.join(fixture.outputDirectory, "latest.json"), "previous output");
      const result = stageFixture(fixture);
      expect(result.status).not.toBe(0);
      expect(combinedOutput(result)).toContain("release note is missing");
      expect(fs.readFileSync(path.join(fixture.outputDirectory, "latest.json"), "utf8")).toBe(
        "previous output",
      );
      expect(fs.readdirSync(path.dirname(fixture.outputDirectory))).toEqual(["windows"]);
    },
    releaseProcessTimeout,
  );

  it(
    "reproduces bytes across reruns and a path containing spaces and an apostrophe",
    () => {
      const fixture = createStagedInstallerFixture();
      const snapshot = () =>
        fs
          .readdirSync(fixture.outputDirectory)
          .map((name) => [
            name,
            fs.readFileSync(path.join(fixture.outputDirectory, name)).toString("hex"),
          ]);
      const before = snapshot();
      expect(stageFixture(fixture).status).toBe(0);
      expect(snapshot()).toEqual(before);
      const other = {
        ...fixture,
        outputDirectory: path.join(fixture.root, "operator's output", "Windows assets"),
      };
      expect(stageFixture(other).status).toBe(0);
      for (const name of fs.readdirSync(fixture.outputDirectory)) {
        expect(fs.readFileSync(path.join(other.outputDirectory, name))).toEqual(
          fs.readFileSync(path.join(fixture.outputDirectory, name)),
        );
      }
    },
    releaseProcessTimeout,
  );

  it(
    "keeps installer-only manual builds usable without signatures or release notes",
    () => {
      const fixture = createBundleFixture({ releaseNote: null });
      for (const relativePath of [
        "nsis/Archeion_0.3.0_x64-setup.exe.sig",
        "msi/Archeion_0.3.0_x64_en-US.msi.sig",
      ])
        fs.rmSync(path.join(fixture.bundleRoot, relativePath));
      const result = stageFixture(fixture, ["--installers-only"]);
      expect(result.status, combinedOutput(result)).toBe(0);
      expect(fs.readdirSync(fixture.outputDirectory).sort()).toEqual([
        "Archeion-Setup-x64.exe",
        "Archeion-x64.msi",
        "SHA256SUMS.txt",
      ]);
      expect(
        runPowerShell("verify-windows-release.ps1", [
          "--artifacts-dir",
          fixture.outputDirectory,
          "--project",
          fixture.root,
        ]).status,
      ).not.toBe(0);
    },
    releaseProcessTimeout,
  );

  it.each(["project", "bundle", "Git metadata", "unknown output"])(
    "refuses destructive replacement of %s",
    (target) => {
      const fixture = createBundleFixture();
      if (target === "project") fixture.outputDirectory = fixture.root;
      else if (target === "bundle") fixture.outputDirectory = fixture.bundleRoot;
      else if (target === "Git metadata")
        fixture.outputDirectory = path.join(fixture.root, ".git", "staged");
      else {
        fs.mkdirSync(fixture.outputDirectory, { recursive: true });
        fs.writeFileSync(path.join(fixture.outputDirectory, "keep.txt"), "user-owned");
      }
      const result = stageFixture(fixture);
      expect(result.status).not.toBe(0);
      expect(combinedOutput(result)).toMatch(/Unsafe output directory|unexpected output content/);
      expect(fs.existsSync(path.join(fixture.root, "package.json"))).toBe(true);
      expect(
        fs.existsSync(path.join(fixture.bundleRoot, "nsis/Archeion_0.3.0_x64-setup.exe")),
      ).toBe(true);
      if (target === "unknown output")
        expect(fs.readFileSync(path.join(fixture.outputDirectory, "keep.txt"), "utf8")).toBe(
          "user-owned",
        );
    },
  );

  it(
    "rejects semantic manifest drift even after its checksum has been recomputed",
    () => {
      const { root, outputDirectory } = createStagedInstallerFixture();
      const manifestPath = path.join(outputDirectory, "latest.json");
      const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
      manifest.platforms["windows-x86_64-msi"].url = manifest.platforms["windows-x86_64-nsis"].url;
      const contents = JSON.stringify(manifest);
      fs.writeFileSync(manifestPath, contents);
      const checksumPath = path.join(outputDirectory, "SHA256SUMS.txt");
      fs.writeFileSync(
        checksumPath,
        fs
          .readFileSync(checksumPath, "utf8")
          .replace(/^[0-9a-f]{64} {2}latest\.json$/m, `${sha256(contents)}  latest.json`),
      );
      const result = runPowerShell("verify-windows-release.ps1", [
        "--project",
        root,
        "--artifacts-dir",
        outputDirectory,
      ]);
      expect(result.status).not.toBe(0);
      expect(combinedOutput(result)).toContain("[3/3] Verifying update manifest");
      expect(combinedOutput(result)).toContain("latest.json does not match");
    },
    releaseProcessTimeout,
  );

  it.each(["duplicate", "missing", "unexpected", "empty asset"])(
    "rejects %s checksum coverage or payload",
    (variant) => {
      const { root, outputDirectory } = createStagedInstallerFixture();
      const checksumPath = path.join(outputDirectory, "SHA256SUMS.txt");
      const lines = fs.readFileSync(checksumPath, "utf8").trim().split(/\r?\n/);
      if (variant === "duplicate") lines[1] = lines[0];
      else if (variant === "missing") lines.pop();
      else if (variant === "unexpected") lines[1] = `${"0".repeat(64)}  ../outside.exe`;
      else fs.writeFileSync(path.join(outputDirectory, "Archeion-Setup-x64.exe.sig"), "");
      fs.writeFileSync(checksumPath, `${lines.join("\n")}\n`);
      const result = runPowerShell("verify-windows-release.ps1", [
        "--project",
        root,
        "--artifacts-dir",
        outputDirectory,
      ]);
      expect(result.status).not.toBe(0);
      expect(combinedOutput(result)).toMatch(/checksum|nonempty regular file/);
    },
    releaseProcessTimeout,
  );

  it(
    "updates all application version sources as one transaction",
    () => {
      const root = createFixture();
      const result = runPowerShell("set-version.ps1", ["0.4.0-beta.1", "--project", root]);

      const output = combinedOutput(result);
      expectFragmentsInOrder(output, [
        "Updating Archeion to 0.4.0-beta.1",
        "[1/4] Updating npm metadata",
        "[2/4] Updating Cargo metadata",
        "[3/4] Updating Tauri configuration",
        "[4/4] Validating release metadata",
        "Version update complete",
      ]);
      expect(output).toMatch(/Version\s+0\.4\.0-beta\.1/);
      expect(output).toContain("Add the dated changelog section before creating the release tag.");
      expect(result.status).toBe(0);
      expect(readVersions(root)).toEqual({
        packageJson: "0.4.0-beta.1",
        packageLock: "0.4.0-beta.1",
        cargoToml: "0.4.0-beta.1",
        cargoLock: "0.4.0-beta.1",
        tauriConfig: "0.4.0-beta.1",
      });
    },
    releaseProcessTimeout,
  );

  it(
    "restores every version file and reports rollback after validation fails",
    () => {
      const root = createFixture({ invalidCargoMetadata: true });
      const versionPaths = [
        "package.json",
        "package-lock.json",
        "src-tauri/Cargo.toml",
        "src-tauri/Cargo.lock",
        "src-tauri/tauri.conf.json",
      ];
      const before = new Map(
        versionPaths.map((relativePath) => [
          relativePath,
          fs.readFileSync(path.join(root, relativePath), "utf8"),
        ]),
      );

      const result = runPowerShell("set-version.ps1", ["0.4.0", "--project", root]);

      expect(result.status).not.toBe(0);
      expect(combinedOutput(result)).toContain("[4/4] Validating release metadata");
      expect(combinedOutput(result)).toContain(
        "Version update failed. Original version files were restored.",
      );
      for (const relativePath of versionPaths) {
        expect(fs.readFileSync(path.join(root, relativePath), "utf8")).toBe(
          before.get(relativePath),
        );
      }
    },
    releaseProcessTimeout,
  );

  it(
    "keeps permanent staging lifecycle output in plain CI mode",
    () => {
      const root = createFixture();
      const bundleRoot = path.join(root, "bundle");
      const outputDirectory = path.join(root, "artifacts", "windows");
      fs.mkdirSync(path.join(bundleRoot, "nsis"), { recursive: true });
      fs.mkdirSync(path.join(bundleRoot, "msi"), { recursive: true });
      fs.writeFileSync(
        path.join(bundleRoot, "nsis", "Archeion_0.3.0_x64-setup.exe"),
        "fixture NSIS installer",
      );
      fs.writeFileSync(
        path.join(bundleRoot, "msi", "Archeion_0.3.0_x64_en-US.msi"),
        "fixture MSI installer",
      );
      addSignatureFixtures(bundleRoot);

      const result = runPowerShell(
        "stage-windows-release.ps1",
        ["--project", root, "--bundle-dir", bundleRoot, "--output", outputDirectory],
        { CI: "true", NO_COLOR: "1" },
      );

      expect(result.status).toBe(0);
      expectFragmentsInOrder(combinedOutput(result), [
        "[1/4] Validating release metadata",
        "[2/4] Locating Windows installers",
        "[3/4] Staging installers",
        "[4/4] Writing checksum manifest",
        "Windows release staged",
      ]);
    },
    releaseProcessTimeout,
  );

  it("keeps the Windows staging compatibility wrapper as a pass-through", () => {
    const root = createFixture();
    const bundleRoot = path.join(root, "bundle");
    const outputDirectory = path.join(root, "artifacts", "windows");
    fs.mkdirSync(path.join(bundleRoot, "nsis"), { recursive: true });
    fs.mkdirSync(path.join(bundleRoot, "msi"), { recursive: true });
    fs.writeFileSync(
      path.join(bundleRoot, "nsis", "Archeion_0.3.0_x64-setup.exe"),
      "fixture NSIS installer",
    );

    const result = runPowerShell("stage-windows-bundles.ps1", [
      "--project",
      root,
      "--bundle-dir",
      bundleRoot,
      "--output",
      outputDirectory,
    ]);

    expect(result.status).not.toBe(0);
    expect(combinedOutput(result)).toContain("Expected exactly one MSI installer");
    expect(fs.existsSync(outputDirectory)).toBe(false);
  });
});

describe("release operator lifecycle structure", () => {
  it("keeps installer smoke lifecycle steps permanent and ordered", () => {
    const script = fs.readFileSync(path.join(scriptsRoot, "smoke-windows-installer.ps1"), "utf8");

    expectFragmentsInOrder(script, [
      "Write-CliStep -Current 1 -Total 4 -Message 'Installing isolated copy'",
      "Write-CliStep -Current 2 -Total 4 -Message 'Verifying installation'",
      "Write-CliStep -Current 3 -Total 4 -Message 'Uninstalling'",
      "Write-CliStep -Current 4 -Total 4 -Message 'Verifying cleanup'",
      "Write-CliSuccess 'Windows installer smoke passed'",
    ]);
    expect(script).not.toContain("Write-Progress");
    expect(script).toContain(
      "Remove-OwnedPreviousLocation -RegistryPath $previousLocationKey -InstallDirectory $installDirectory",
    );
    expect(script).toContain("elseif (Test-Path -LiteralPath $previousLocationKey)");
    expect(
      script.indexOf("Remove-OwnedPreviousLocation -RegistryPath $previousLocationKey"),
    ).toBeLessThan(script.indexOf("Write-CliSuccess 'Windows installer smoke passed'"));
  });

  it("keeps the Windows staging compatibility wrapper implementation-free", () => {
    const wrapper = fs.readFileSync(path.join(scriptsRoot, "stage-windows-bundles.ps1"), "utf8");

    expect(wrapper).toContain('& (Join-Path $PSScriptRoot "stage-windows-release.ps1") @args');
    expect(wrapper).not.toContain("Write-Cli");
    expect(wrapper).not.toContain("Write-Host");
  });
});

const describeWindowsInstallerSmoke =
  hasReleaseToolchain && process.platform === "win32" ? describe : describe.skip;

function runPreviousLocationCleanupFixture(location: string, expected: string) {
  const script = [
    "$ErrorActionPreference = 'Stop'",
    ". $env:SMOKE_SCRIPT --help | Out-Null",
    "$fixtureKey = 'HKCU:\\Software\\ArcheionSmokeFixture-' + [guid]::NewGuid().ToString('N')",
    "try {",
    "  if (Test-Path -LiteralPath $fixtureKey) { throw 'Fixture key already exists.' }",
    "  New-Item -Path $fixtureKey -Force | Out-Null",
    "  Set-Item -LiteralPath $fixtureKey -Value $env:FIXTURE_LOCATION",
    "  New-ItemProperty -LiteralPath $fixtureKey -Name 'Installer Language' -Value '1033' -PropertyType String | Out-Null",
    "  try {",
    "    Remove-OwnedPreviousLocation -RegistryPath $fixtureKey -InstallDirectory $env:EXPECTED_LOCATION",
    "    Write-Output 'cleanup: removed'",
    "  } catch {",
    "    Write-Output ('cleanup: rejected ' + $_.Exception.Message)",
    "  }",
    "  Write-Output ('key-present: ' + (Test-Path -LiteralPath $fixtureKey))",
    "} finally {",
    "  if (Test-Path -LiteralPath $fixtureKey) { Remove-Item -LiteralPath $fixtureKey -Force -ErrorAction Stop }",
    "}",
  ].join("\n");

  return spawnSync("pwsh", ["-NoProfile", "-NonInteractive", "-Command", script], {
    cwd: projectRoot,
    encoding: "utf8",
    env: {
      ...process.env,
      SMOKE_SCRIPT: path.join(scriptsRoot, "smoke-windows-installer.ps1"),
      FIXTURE_LOCATION: location,
      EXPECTED_LOCATION: expected,
    },
    windowsHide: true,
  });
}

describeWindowsInstallerSmoke("Windows installer smoke", { timeout: releaseProcessTimeout }, () => {
  it("rejects a missing staged installer without touching installation state", () => {
    const root = createFixture();
    const missingInstaller = path.join(root, "missing-setup.exe");
    const result = runPowerShell("smoke-windows-installer.ps1", ["--installer", missingInstaller]);

    expect(result.status).not.toBe(0);
    expect(combinedOutput(result)).toContain("NSIS installer does not exist:");
    expect(combinedOutput(result)).toContain("missing-setup.exe");
  });

  it("rejects an invalid installer fixture before executing it", () => {
    const root = createFixture();
    const invalidInstaller = path.join(root, "invalid-setup.exe");
    fs.writeFileSync(invalidInstaller, "not a Windows executable");
    const result = runPowerShell("smoke-windows-installer.ps1", ["--installer", invalidInstaller]);

    expect(result.status).not.toBe(0);
    expect(combinedOutput(result)).toContain("NSIS installer is not a Windows executable");
  });

  it("removes only a previous-location marker owned by the isolated install", () => {
    const isolatedInstall = path.join(os.tmpdir(), "archeion-smoke-fixture", "installed");
    const result = runPreviousLocationCleanupFixture(isolatedInstall, isolatedInstall);

    expect(result.status).toBe(0);
    expect(combinedOutput(result)).toContain("cleanup: removed");
    expect(combinedOutput(result)).toContain("key-present: False");
  });

  it("refuses to remove a previous-location marker pointing outside the isolated install", () => {
    const isolatedInstall = path.join(os.tmpdir(), "archeion-smoke-fixture", "installed");
    const otherInstall = path.join(os.tmpdir(), "different-install");
    const result = runPreviousLocationCleanupFixture(otherInstall, isolatedInstall);

    expect(result.status).toBe(0);
    expect(combinedOutput(result)).toContain("cleanup: rejected Refusing to clean");
    expect(combinedOutput(result)).toContain("key-present: True");
  });
});
