export const settingsSections = [
  {
    id: "general",
    label: "General",
    searchTerms: [
      "general",
      "startup behavior",
      "startup",
      "open last archive",
      "archive manager",
      "destructive",
      "confirm destructive file actions",
      "confirm",
      "restore last reader route",
      "restore reader",
      "reopen last book route",
      "window behavior",
      "window",
      "size",
      "position",
      "remember window size and position",
    ],
  },
  {
    id: "appearance",
    label: "Appearance",
    searchTerms: [
      "appearance",
      "app appearance",
      "custom theme",
      "theme manager",
      "theme import",
      "theme",
      "display density",
      "animations",
      "motion",
      "transitions",
      "density",
      "accent",
      "compact",
    ],
  },
  {
    id: "library",
    label: "Library",
    searchTerms: [
      "library",
      "books",
      "folders",
      "series",
      "grid",
      "cards",
      "list",
      "sort",
      "default view",
      "default sort",
      "title",
      "author",
      "name",
      "path",
      "recently opened",
      "book count",
      "volume count",
      "most books",
      "most volumes",
      "book card size",
      "folder card size",
      "series card size",
      "card size",
      "show continue reading",
      "continue reading",
      "smart views",
      "unread",
      "in progress",
      "completed",
      "needs metadata",
      "needs cover",
      "cover size",
    ],
  },
  {
    id: "reader",
    label: "Reader",
    searchTerms: [
      "reader",
      "font family",
      "font size",
      "font",
      "typeface",
      "line height",
      "page margin",
      "margin",
      "reader theme",
      "theme",
      "progress placement",
      "progress",
      "wheel",
      "reading position",
      "epub reader",
    ],
  },
  {
    id: "archives",
    label: "Archives",
    searchTerms: [
      "archives",
      "archive folder",
      "current archive folder",
      "current archive",
      "manager",
      "archive manager",
      "reveal folder",
      "import",
      "default import mode",
      "copy",
      "move",
      "default conflict handling",
      "conflict",
      "default destination folder",
      "destination",
      "epub",
    ],
  },
  {
    id: "storage",
    label: "Storage",
    searchTerms: [
      "storage",
      "file monitoring",
      "archive scanning",
      "generated cover cache",
      "epub writeback backups",
      "archive metadata and recovery",
      "files",
      "metadata",
      "scan on startup",
      "scan",
      "rescan archive",
      "rescan",
      "scanner cache",
      "cache",
      "cover cache status",
      "cover",
      "live filesystem watcher",
      "watcher",
      "live refresh",
      "re-extract epub source metadata",
      "re-extract source metadata",
      "source metadata",
      "sidecar metadata",
      "recovery",
      "reset storage preferences",
      ".archeion",
      ".archeion folder",
      "archeion folder",
    ],
  },
  {
    id: "dictionaries",
    label: "Dictionaries",
    searchTerms: [
      "dictionaries",
      "dictionary",
      "lookup",
      "available dictionaries",
      "installed dictionaries",
      "stardict",
      "import dictionary",
      "download dictionary",
    ],
  },
  {
    id: "keyboard",
    label: "Keyboard",
    searchTerms: [
      "keyboard",
      "shortcut",
      "shortcuts",
      "hotkey",
      "key binding",
      "quick actions",
      "settings shortcut",
      "focus search",
      "reader keys",
      "escape",
    ],
  },
] as const;

export type SettingsSection = (typeof settingsSections)[number]["id"];

const searchTermsBySection = new Map<SettingsSection, readonly string[]>(
  settingsSections.map((section) => [section.id, section.searchTerms]),
);

export function sectionMatches(section: SettingsSection, query: string) {
  const normalized = query.trim().toLocaleLowerCase();
  if (!normalized) return true;
  return searchTermsBySection.get(section)?.some((entry) => entry.includes(normalized)) ?? false;
}
