export const settingsSections = [
  {
    id: "general",
    label: "General",
    searchTerms: [
      "general",
      "startup behavior",
      "startup",
      "open last archive",
      "archive manager",
      "destructive",
      "confirm destructive file actions",
      "confirm",
      "restore last reader route",
      "restore reader",
      "reopen last book route",
    ],
  },
  {
    id: "library",
    label: "Library",
    searchTerms: [
      "library",
      "grid",
      "list",
      "sort",
      "default view",
      "default sort",
      "title",
      "author",
      "recently opened",
      "book card size",
      "card size",
      "show continue reading",
      "continue reading",
      "smart views",
      "unread",
      "in progress",
      "completed",
      "needs metadata",
      "needs cover",
      "cover size",
    ],
  },
  {
    id: "reader",
    label: "Reader",
    searchTerms: [
      "reader",
      "font family",
      "font size",
      "font",
      "typeface",
      "line height",
      "page margin",
      "margin",
      "reader theme",
      "theme",
      "progress placement",
      "progress",
      "wheel",
      "reading position",
      "epub reader",
    ],
  },
  {
    id: "appearance",
    label: "Appearance",
    searchTerms: [
      "appearance",
      "app appearance",
      "window behavior",
      "app theme preset",
      "theme",
      "display density",
      "animations",
      "motion",
      "transitions",
      "density",
      "accent",
      "compact",
      "window",
      "window frame style",
      "frame",
      "hidden",
      "archeion",
      "native",
      "size",
      "position",
      "remember window size and position",
      "chrome",
    ],
  },
  {
    id: "archives",
    label: "Archives",
    searchTerms: [
      "archives",
      "archive folder",
      "current archive folder",
      "current archive",
      "manager",
      "archive manager",
      "reveal folder",
    ],
  },
  {
    id: "storage",
    label: "Storage",
    searchTerms: [
      "storage",
      "scan preferences",
      "archive maintenance",
      "files",
      "metadata",
      "scan on startup",
      "scan",
      "rescan archive",
      "rescan",
      "scanner cache",
      "cache",
      "cover cache status",
      "cover",
      "live filesystem watcher",
      "watcher",
      "live refresh",
      "re-extract epub source metadata",
      "re-extract source metadata",
      "source metadata",
      ".archeion",
      ".archeion folder",
      "archeion folder",
    ],
  },
  {
    id: "import",
    label: "Import",
    searchTerms: [
      "import",
      "default import mode",
      "copy",
      "move",
      "default conflict handling",
      "conflict",
      "default destination folder",
      "destination",
      "epub",
    ],
  },
] as const;

export type SettingsSection = (typeof settingsSections)[number]["id"];

const searchTermsBySection = new Map<SettingsSection, readonly string[]>(
  settingsSections.map((section) => [section.id, section.searchTerms]),
);

export function sectionMatches(section: SettingsSection, query: string) {
  const normalized = query.trim().toLocaleLowerCase();
  if (!normalized) return true;
  return searchTermsBySection.get(section)?.some((entry) => entry.includes(normalized)) ?? false;
}
